# Generated by Django 5.0.4 on 2024-04-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_sal', models.IntegerField()),
                ('company_name', models.CharField(max_length=20)),
                ('work_mode', models.CharField(choices=[('WFH', 'Work From Home'), ('WFO', 'Work From Office')], max_length=10)),
            ],
        ),
    ]
